import fs from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'

// Reviewed CGs are source-controlled art. This command only fills a missing rain
// sprite; it must never recreate retired placeholder CGs or overwrite real art.
const OUT_DIR = path.resolve(process.cwd(), 'public', 'assets', 'images')
const RAIN_PATH = path.join(OUT_DIR, 'vfx_rain_sprite.webp')
const args = process.argv.slice(2)
if (args.some((arg) => arg !== '--force')) {
  throw new Error('Usage: node scripts/generate_assets.mjs [--force]')
}
const forceRain = args.includes('--force')

const rainSpriteSheet = () => {
  const frameSize = 128
  const columns = 4
  const rows = 4
  const frames = Array.from({ length: columns * rows }, (_, index) => {
    const x0 = (index % columns) * frameSize
    const y0 = Math.floor(index / columns) * frameSize
    return Array.from({ length: 10 }, (_, drop) => {
      const x = x0 + 10 + ((index * 41 + drop * 13) % (frameSize - 20))
      const y = y0 + 8 + ((index * 17 + drop * 29) % (frameSize - 40))
      const length = 16 + ((index + drop) % 10)
      const opacity = 0.18 + ((index + drop) % 7) / 30
      return `<line x1="${x}" y1="${y}" x2="${x + 4}" y2="${y + length}"
        stroke="#8be9fd" stroke-width="2" stroke-opacity="${opacity}"/>`
    }).join('')
  }).join('\n')

  return `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"
    viewBox="0 0 512 512"><rect width="512" height="512" fill="none"/>${frames}</svg>`
}

const main = async () => {
  await fs.mkdir(OUT_DIR, { recursive: true })
  if (!forceRain) {
    try {
      await fs.access(RAIN_PATH)
      console.log('Kept existing rain sprite; reviewed CGs are never generated by this command.')
      return
    } catch (error) {
      if (error.code !== 'ENOENT') throw error
    }
  }

  const buffer = await sharp(Buffer.from(rainSpriteSheet()))
    .webp({ quality: 70, effort: 6 })
    .toBuffer()
  // Exclusive creation also protects a file added after the existence check.
  await fs.writeFile(RAIN_PATH, buffer, { flag: forceRain ? 'w' : 'wx' })
  console.log('Generated vfx_rain_sprite.webp; no CG or placeholder files were written.')
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
