"""Regenerate checked-in WOFF2 subsets: python -m pip install fonttools brotli."""
from hashlib import sha256
from io import BytesIO
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'public/assets/fonts/HYPixel11pxU-2.ttf'
OUT = SOURCE.parent


def unicode_ranges(codepoints):
    ranges = []
    ordered = sorted(codepoints)
    start = end = ordered[0]
    for point in ordered[1:]:
        if point == end + 1:
            end = point
        else:
            ranges.append((start, end))
            start = end = point
    ranges.append((start, end))
    return ','.join(f'U+{a:X}' if a == b else f'U+{a:X}-{b:X}' for a, b in ranges)


def make_font(label, codepoints):
    font = TTFont(SOURCE, recalcTimestamp=False)
    options = subset.Options()
    options.name_IDs = ['*']  # Preserve source attribution and license metadata.
    worker = subset.Subsetter(options=options)
    worker.populate(unicodes=codepoints)
    worker.subset(font)
    font.flavor = 'woff2'
    output = BytesIO()
    font.save(output)
    data = output.getvalue()
    name = f'hanyi-{label}-{sha256(data).hexdigest()[:12]}.woff2'
    (OUT / name).write_bytes(data)
    # Verify the serialized artifact, not only the input sets.
    assert set(TTFont(BytesIO(data)).getBestCmap()) == codepoints
    print(f'{label}: {len(codepoints)} characters, {len(data)} bytes')
    return f'''@font-face {{
  font-family: "HanYiPixel11";
  src: url("/assets/fonts/{name}") format("woff2");
  font-display: swap;
  font-weight: 400 900;
  font-style: normal;
  unicode-range: {unicode_ranges(codepoints)};
}}
'''


if __name__ == '__main__':
    supported = set(TTFont(SOURCE).getBestCmap())
    text = ''.join(p.read_text(encoding='utf-8') for p in (ROOT / 'src').rglob('*')
                   if p.suffix in {'.vue', '.ts', '.css'} and p.name != 'fonts.generated.css')
    core = ({ord(c) for c in text} | set(range(0x20, 0x7F))) & supported
    remainder = supported - core
    assert not core & remainder and core | remainder == supported
    css = '/* Generated by scripts/generate_fonts.py; do not edit. */\n'
    css += make_font('ui', core) + make_font('rest', remainder)
    (ROOT / 'src/fonts.generated.css').write_text(css, encoding='utf-8')
